# docker-compose.yml

version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jackobo97.
    ports:
      - "5432:5432"
    volumes:
      - hotel_api-db:/var/lib/postgresql/data

  hotel_api:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: Jackobo97.
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  hotel_api-db:
